module:
  hugoVersion:
    min: '0.64.0'
  mounts:
    - source: page/index.md
      target: content/radixicons.md
      lang: en
    - source: page/template.html
      target: layouts/_default/radixicons.html
    - source: partials
      target: layouts/partials/radix
  imports:
    - path: github.com/modulz/radix-icons
      mounts:
      - source: packages/radix-icons/icons/15
        target: assets/radix-icons/icons
